# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HZCodingSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HZCodingSwiftDemo
pod 'NSObject+HZCoding', '~> 1.2.0'
 
end
