# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HZCodingDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HZCodingDemo

 pod 'NSObject+HZCoding', '~> 1.2.0'

end
